import { Activity, Bot, ChevronDown, ChevronUp, ClipboardPlus, FileText, FlaskConical, Plus, Stethoscope } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { createHealthRecord, fetchHealthRecords } from '../features/patient-timeline/healthRecordService'
import type { HealthRecord, HealthRecordType } from '../features/patient-timeline/types'
import { generateAiHealthSummary, type AiHealthSummary } from '../features/patient-timeline/aiHealthSummaryService'
import { useAuth } from '../features/auth/AuthContext'

type TimelineFilter = 'all' | 'consultation' | 'diagnosis' | 'treatment' | 'medication' | 'test' | 'procedure' | 'other'
const filters: Array<{ label: string; value: TimelineFilter }> = [{ label: 'All', value: 'all' }, { label: 'Consultations', value: 'consultation' }, { label: 'Diagnoses', value: 'diagnosis' }, { label: 'Treatments', value: 'treatment' }, { label: 'Medications', value: 'medication' }, { label: 'Tests', value: 'test' }, { label: 'Procedures', value: 'procedure' }, { label: 'Other', value: 'other' }]
const typeLabels: Record<HealthRecordType, string> = { consultation: 'Consultation', diagnosis: 'Diagnosis', treatment: 'Treatment', medication: 'Medication', test: 'Test', procedure: 'Procedure', vaccination: 'Vaccination', allergy: 'Allergy', other: 'Other' }
const eventVisuals: Record<HealthRecordType, { icon: typeof Stethoscope; className: string }> = { consultation: { icon: Stethoscope, className: 'consultation' }, diagnosis: { icon: Activity, className: 'treatment' }, treatment: { icon: Activity, className: 'treatment' }, medication: { icon: FileText, className: 'record' }, test: { icon: FlaskConical, className: 'diagnostic' }, procedure: { icon: Stethoscope, className: 'consultation' }, vaccination: { icon: FileText, className: 'record' }, allergy: { icon: FileText, className: 'record' }, other: { icon: FileText, className: 'record' } }
const initialForm = { record_type: 'consultation' as HealthRecordType, title: '', event_date: new Date().toISOString().slice(0, 10), description: '', provider_name: '', facility_name: '' }
function displayDate(value: string) { return new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) }
function recordSignature(records: HealthRecord[]) { return records.map((record) => `${record.id}:${record.updated_at}`).sort().join('|') }

export function PatientTimeline() {
  const { profile } = useAuth()
  const [records, setRecords] = useState<HealthRecord[]>([]); const [filter, setFilter] = useState<TimelineFilter>('all'); const [summaryOpen, setSummaryOpen] = useState(true); const [summary, setSummary] = useState<AiHealthSummary | null>(null); const [summaryError, setSummaryError] = useState<string | null>(null); const [generatingSummary, setGeneratingSummary] = useState(false); const [summaryRecordSignature, setSummaryRecordSignature] = useState<string | null>(null); const [expandedRecordId, setExpandedRecordId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState<string | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(initialForm); const [formError, setFormError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const loadRecords = useCallback(async () => { if (!profile) return; setLoading(true); setLoadError(null); try { setRecords(await fetchHealthRecords(profile.id)) } catch (error) { setLoadError(error instanceof Error ? error.message : 'Unable to load health records.') } finally { setLoading(false) } }, [profile])
  useEffect(() => { void loadRecords() }, [loadRecords])
  const currentRecordSignature = useMemo(() => recordSignature(records), [records])
  const summaryNeedsRefresh = Boolean(summary && summaryRecordSignature !== currentRecordSignature)
  const generateSummary = async () => { setGeneratingSummary(true); setSummaryError(null); try { const nextSummary = await generateAiHealthSummary(); setSummary(nextSummary); setSummaryRecordSignature(currentRecordSignature) } catch (error) { setSummaryError(error instanceof Error ? error.message : 'Unable to generate your AI health summary.') } finally { setGeneratingSummary(false) } }
  const filteredRecords = useMemo(() => filter === 'all' ? records : filter === 'other' ? records.filter((record) => ['vaccination', 'allergy', 'other'].includes(record.record_type)) : records.filter((record) => record.record_type === filter), [filter, records])
  const recordsByYear = useMemo(() => filteredRecords.reduce<Record<number, HealthRecord[]>>((groups, record) => { const year = Number(record.event_date.slice(0, 4)); groups[year] = [...(groups[year] ?? []), record]; return groups }, {}), [filteredRecords])
  const startRecord = () => { setForm(initialForm); setFormError(null); setFormOpen(true) }
  const saveRecord = async () => { if (!profile || !form.title.trim() || !form.event_date) { setFormError('Add a title and date before saving.'); return } setSaving(true); setFormError(null); try { const created = await createHealthRecord({ patient_id: profile.id, record_type: form.record_type, title: form.title.trim(), description: form.description.trim() || null, event_date: form.event_date, provider_name: form.provider_name.trim() || null, facility_name: form.facility_name.trim() || null, diagnosis: null, metadata: {} }); setRecords((current) => [created, ...current].sort((a, b) => b.event_date.localeCompare(a.event_date))); setFormOpen(false) } catch (error) { setFormError(error instanceof Error ? error.message : 'Unable to save this health record.') } finally { setSaving(false) } }
  return <div className="timeline-page"><header className="timeline-header"><div><p className="dashboard-date">Your care journey</p><h2>Health timeline</h2><p>A structured view of your health history and care journey.</p></div><div className="timeline-header-actions"><button className="add-record-button" type="button" onClick={startRecord}><Plus size={17} />Add health record</button><button className="ai-summary-button" type="button" onClick={() => setSummaryOpen(!summaryOpen)} aria-expanded={summaryOpen} aria-controls="ai-health-summary"><Bot size={18} />AI Summary {summaryOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}</button></div></header>
    <section className={summaryOpen ? 'health-summary expanded' : 'health-summary'} id="ai-health-summary" aria-label="PreScribe AI Health Summary">
      <div className="summary-heading"><span className="summary-icon"><Bot size={19} /></span><div><p className="section-kicker">PreScribe AI</p><h3>Health Summary</h3></div></div>
      {summaryOpen && <div className="summary-content">
        <p className="summary-disclaimer">AI-generated summary based only on your recorded health information. This summary is informational and does not provide a diagnosis or replace professional medical advice.</p>
        {summaryNeedsRefresh && <p className="summary-stale">Your health records have changed. Refresh the AI summary to include your latest information.</p>}
        {summaryError && <p className="form-message error">{summaryError}</p>}
        {!summary && !generatingSummary && <p>{records.length ? `${records.length} health record${records.length === 1 ? '' : 's'} are available for an on-demand summary.` : 'No health records are available yet. You can still check the summary status.'}</p>}
        {generatingSummary && <p>Generating your health summary from your recorded information…</p>}
        {summary && !generatingSummary && <div className="ai-health-result">
          {summary.hasRecords ? <>
            <SummarySection title="Health overview"><p>{summary.overview}</p></SummarySection>
            <SummaryList title="Key events" items={summary.keyEvents.map((event) => <li key={`${event.date ?? 'unknown'}-${event.title}`}><b>{event.date ? displayDate(event.date) : 'Date not recorded'} · {event.title}</b><span>{event.summary}</span></li>)} />
            <SummaryList title="Possible record patterns" items={summary.patterns.map((pattern) => <li key={pattern}>{pattern}</li>)} empty="No directly supported patterns were identified in your records." />
            <SummaryList title="Topics to discuss with a healthcare professional" items={summary.followUpTopics.map((topic) => <li key={topic}>{topic}</li>)} empty="No follow-up topics were identified from the available records." />
            <SummaryList title="Limitations" items={summary.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)} />
          </> : <SummaryList title="Limitations" items={summary.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)} />}
        </div>}
        <button className="summary-generate-button" type="button" onClick={() => void generateSummary()} disabled={generatingSummary}>{generatingSummary ? 'Generating…' : summary ? 'Refresh Summary' : 'Generate AI Summary'}</button>
      </div>}
    </section>
    {formOpen && <section className="health-record-form" aria-labelledby="add-record-heading"><div className="record-form-heading"><div><p className="section-kicker">Personal health history</p><h3 id="add-record-heading">Add health record</h3></div><button type="button" className="record-form-close" onClick={() => setFormOpen(false)}>Cancel</button></div><div className="record-form-grid"><label>Record type<select value={form.record_type} onChange={(event) => setForm({ ...form, record_type: event.target.value as HealthRecordType })}>{Object.entries(typeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Date<input type="date" value={form.event_date} onChange={(event) => setForm({ ...form, event_date: event.target.value })} /></label><label className="record-form-wide">Title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="For example, Annual wellness visit" /></label><label className="record-form-wide">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Optional details you want to keep with this record" rows={3} /></label><label>Doctor or provider<input value={form.provider_name} onChange={(event) => setForm({ ...form, provider_name: event.target.value })} placeholder="Optional" /></label><label>Hospital or facility<input value={form.facility_name} onChange={(event) => setForm({ ...form, facility_name: event.target.value })} placeholder="Optional" /></label></div>{formError && <p className="form-message error">{formError}</p>}<div className="record-form-actions"><button type="button" className="booking-back" onClick={() => setFormOpen(false)}>Cancel</button><button type="button" className="booking-next" onClick={() => void saveRecord()} disabled={saving}>{saving ? 'Saving…' : 'Save health record'}</button></div></section>}
    <section className="timeline-controls" aria-label="Timeline filters"><p className="section-kicker">Filter timeline</p><div className="timeline-filter-list">{filters.map((item) => <button type="button" key={item.value} className={filter === item.value ? 'timeline-filter active' : 'timeline-filter'} onClick={() => setFilter(item.value)} aria-pressed={filter === item.value}>{item.label}</button>)}</div></section>
    <section className="timeline-list" aria-live="polite">{loading ? <div className="empty-timeline"><p>Loading your health records…</p></div> : loadError ? <div className="empty-timeline error"><p>{loadError}</p><button type="button" className="text-action" onClick={() => void loadRecords()}>Try again</button></div> : Object.entries(recordsByYear).sort(([first], [second]) => Number(second) - Number(first)).map(([year, yearRecords]) => <div className="timeline-year" key={year}><h3>{year}</h3><div className="timeline-events">{yearRecords.map((record) => <TimelineEventCard record={record} expanded={expandedRecordId === record.id} onToggle={() => setExpandedRecordId(expandedRecordId === record.id ? null : record.id)} key={record.id} />)}</div></div>)}{!loading && !loadError && filteredRecords.length === 0 && <div className="empty-timeline"><ClipboardPlus size={22} /><div><h4>{records.length ? 'No records match this filter.' : 'No health records yet'}</h4><p>{records.length ? 'Choose another category to view your records.' : 'Add your first health record to begin your timeline.'}</p>{records.length === 0 && <button type="button" className="text-action" onClick={startRecord}>Add health record <Plus size={15} /></button>}</div></div>}</section>
  </div>
}

function TimelineEventCard({ record, expanded, onToggle }: { record: HealthRecord; expanded: boolean; onToggle: () => void }) { const visual = eventVisuals[record.record_type]; const Icon = visual.icon; return <article className={`timeline-event ${expanded ? 'expanded' : ''}`}><div className={`event-marker ${visual.className}`}><Icon size={17} /></div><button className="timeline-event-main" type="button" onClick={onToggle} aria-expanded={expanded}><div className="event-meta"><span>{typeLabels[record.record_type]}</span><time>{displayDate(record.event_date)}</time></div><div className="event-title-row"><div><h4>{record.title}</h4>{record.provider_name && <p>{record.provider_name}{record.facility_name ? ` · ${record.facility_name}` : ''}</p>}</div></div>{record.description && <p className="event-description">{record.description}</p>}<span className="event-detail-toggle">{expanded ? 'Hide details' : 'View details'} {expanded ? <ChevronUp size={15} /> : <ChevronDown size={15} />}</span></button>{expanded && <div className="event-details"><dl><div><dt>Date</dt><dd>{displayDate(record.event_date)}</dd></div>{record.provider_name && <div><dt>Provider</dt><dd>{record.provider_name}</dd></div>}{record.facility_name && <div><dt>Facility</dt><dd>{record.facility_name}</dd></div>}{record.diagnosis && <div><dt>Diagnosis</dt><dd>{record.diagnosis}</dd></div>}</dl>{record.description && <p><b>Notes</b>{record.description}</p>}</div>}</article> }

function SummarySection({ title, children }: { title: string; children: ReactNode }) { return <section className="ai-summary-section"><h4>{title}</h4>{children}</section> }
function SummaryList({ title, items, empty }: { title: string; items: ReactNode[]; empty?: string }) { return <SummarySection title={title}>{items.length ? <ul>{items}</ul> : empty ? <p>{empty}</p> : null}</SummarySection> }
