import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, Stethoscope, UserRound } from 'lucide-react'
import { FormEvent, useState } from 'react'
import type { Role } from '../components/auth/RoleSelector'
import { PreScribeMark } from '../components/ui/PreScribeMark'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'

export function SignupPage({ role }: { role: Role }) {
  const isDoctor = role === 'doctor'
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false)
  const { signUp, isConfigured } = useAuth(); const navigate = useNavigate()
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setMessage(null); if (fullName.trim().length < 2) { setError('Enter your full name.'); return }; if (!/^\S+@\S+\.\S+$/.test(email)) { setError('Enter a valid email address.'); return }; if (password.length < 8) { setError('Use at least 8 characters for your password.'); return }; if (password !== confirmPassword) { setError('Passwords do not match.'); return }; setSubmitting(true); const result = await signUp({ fullName: fullName.trim(), email, password, role }); setSubmitting(false); if (result.error) { setError(result.error); return }; if (result.requiresEmailConfirmation) { setMessage('Account created. Check your email to confirm your address, then return to sign in.'); return }; navigate(`/${role}/dashboard`) }
  return <main className={`signup-page ${role}-mode`}><div className="signup-card"><PreScribeMark /><Link className="back-link" to="/"><ArrowLeft size={16} /> Back to sign in</Link><div className="signup-icon">{isDoctor ? <Stethoscope size={26} /> : <UserRound size={26} />}</div><p className="portal-label">{isDoctor ? 'Doctor portal' : 'Patient portal'}</p><h1>Create your account</h1><p>{isDoctor ? 'Set up your secure clinical workspace.' : 'Start a more connected health journey.'}</p><form className="signup-form" onSubmit={submit}><label>Full name<span className="field"><UserRound size={17} /><input value={fullName} onChange={(event) => setFullName(event.target.value)} autoComplete="name" /></span></label><label>Email<span className="field"><Mail size={17} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></span></label><label>Password<span className="field"><LockKeyhole size={17} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /><button className="icon-button" type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><label>Confirm password<span className="field"><LockKeyhole size={17} /><input type={showPassword ? 'text' : 'password'} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} autoComplete="new-password" /></span></label>{error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}{!isConfigured && <p className="form-message">Authentication is awaiting secure Supabase configuration.</p>}<button className="primary-button" type="submit" disabled={submitting}>{submitting ? 'Creating your account…' : `Create ${isDoctor ? 'doctor' : 'patient'} account`}</button></form></div></main>
}
