import type { TimelineEvent, TimelineEventType } from './types'

export const timelineFilters: Array<'All Events' | TimelineEventType> = ['All Events', 'Consultation', 'Treatment', 'Diagnostic Test', 'Health Record']

export const patientTimelineEvents: TimelineEvent[] = [
  { id: 'consult-2026-09', year: 2026, date: '5 September 2026', type: 'Consultation', title: 'Follow-up consultation', provider: 'Dr. Ananya Sharma · General Medicine', description: 'Review of current symptoms and care plan before your next follow-up.', status: 'Scheduled', details: { relatedCare: 'Vitamin D3 supplement plan', notes: 'Bring any questions about recent changes in energy levels or mobility.' } },
  { id: 'treatment-2026-08', year: 2026, date: '20 August 2026', type: 'Treatment', title: 'Vitamin D3 supplement plan', provider: 'Dr. Ananya Sharma', description: 'Supplement support added to your current treatment plan.', status: 'Active', details: { relatedCare: 'General medicine follow-up', notes: 'Taken once daily as directed. Review at your next consultation.' } },
  { id: 'record-2026-06', year: 2026, date: '14 June 2026', type: 'Health Record', title: 'Annual wellness record', provider: 'PreScribe record upload', description: 'A wellness visit summary was added to your health record.', details: { notes: 'Record includes routine observations and preventive care guidance from your visit.' } },
  { id: 'diagnostic-2025-11', year: 2025, date: '11 November 2025', type: 'Diagnostic Test', title: 'Routine blood test results', provider: 'City Diagnostics Laboratory', description: 'Routine blood work results are available in your health record.', status: 'Reviewed', details: { relatedCare: 'General medicine consultation', notes: 'Discussed with your healthcare professional during the November consultation.' } },
  { id: 'consult-2025-10', year: 2025, date: '28 October 2025', type: 'Consultation', title: 'Physiotherapy assessment', provider: 'Riya Nair, PT · Mobility Care', description: 'Initial assessment to support mobility and recovery goals.', status: 'Completed', details: { relatedCare: 'Physiotherapy plan', notes: 'A home movement plan and three weekly sessions were recommended.' } },
  { id: 'treatment-2025-10', year: 2025, date: '30 October 2025', type: 'Treatment', title: 'Physiotherapy plan started', provider: 'Riya Nair, PT', description: 'A structured movement and recovery plan was started.', status: 'Active', details: { relatedCare: 'Physiotherapy assessment', notes: 'Complete the prescribed sessions and discuss progress at the next assessment.' } },
]
