import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' }
const schema = { type: 'object', additionalProperties: false, required: ['appointmentContext', 'consultationOverview', 'patientConcerns', 'relevantHealthHistory', 'activeTreatments', 'activeMedications', 'topicsToDiscuss', 'informationGaps', 'disclaimer', 'generatedAt'], properties: { appointmentContext: { type: 'object', additionalProperties: false, required: ['date', 'type', 'reason'], properties: { date: { type: 'string' }, type: { type: 'string' }, reason: { type: ['string', 'null'] } } }, consultationOverview: { type: 'string' }, patientConcerns: { type: 'array', items: { type: 'string' } }, relevantHealthHistory: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['date', 'title', 'summary'], properties: { date: { type: ['string', 'null'] }, title: { type: 'string' }, summary: { type: 'string' } } } }, activeTreatments: { type: 'array', items: { type: 'string' } }, activeMedications: { type: 'array', items: { type: 'string' } }, topicsToDiscuss: { type: 'array', items: { type: 'string' } }, informationGaps: { type: 'array', items: { type: 'string' } }, disclaimer: { type: 'string' }, generatedAt: { type: 'string' } } }
const instructions = `You are PreScribe AI. Organize supplied patient information only to prepare for a healthcare consultation. Never invent diagnoses, symptoms, dates, medications, treatments, providers, or events; never claim certainty, prescribe treatment, recommend medication changes, provide emergency triage, or replace professional advice. Patient-provided concerns are unverified concerns, not medical records. State unavailable or incomplete information in informationGaps. TopicsToDiscuss must be discussion topics, not recommendations. Return only the requested JSON.`

function isString(value: unknown): value is string { return typeof value === 'string' }
function isSummary(value: unknown): value is Record<string, unknown> { if (!value || typeof value !== 'object') return false; const summary = value as Record<string, unknown>; const context = summary.appointmentContext as Record<string, unknown> | undefined; const events = summary.relevantHealthHistory; return !!context && isString(context.date) && isString(context.type) && (context.reason === null || isString(context.reason)) && isString(summary.consultationOverview) && [summary.patientConcerns, events, summary.activeTreatments, summary.activeMedications, summary.topicsToDiscuss, summary.informationGaps].every(Array.isArray) && (events as unknown[]).every((event) => event && typeof event === 'object' && ((event as Record<string, unknown>).date === null || isString((event as Record<string, unknown>).date)) && isString((event as Record<string, unknown>).title) && isString((event as Record<string, unknown>).summary)) && [summary.patientConcerns, summary.activeTreatments, summary.activeMedications, summary.topicsToDiscuss, summary.informationGaps].every((items) => (items as unknown[]).every(isString)) && isString(summary.disclaimer) }

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  try {
    const authorization = request.headers.get('Authorization')
    if (!authorization) return Response.json({ error: 'Authentication is required.' }, { status: 401, headers: corsHeaders })
    const db = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!, { global: { headers: { Authorization: authorization } } })
    const { data: { user }, error: userError } = await db.auth.getUser()
    if (userError || !user) return Response.json({ error: 'Authentication is required.' }, { status: 401, headers: corsHeaders })
    const { data: profile, error: profileError } = await db.from('profiles').select('role').eq('id', user.id).maybeSingle()
    if (profileError) { console.error('Pre-consultation role lookup failed', profileError); return Response.json({ error: 'Unable to verify your portal access.' }, { status: 500, headers: corsHeaders }) }
    if (profile?.role !== 'patient') return Response.json({ error: 'Only patient accounts can generate a consultation summary.' }, { status: 403, headers: corsHeaders })
    const body = await request.json(); const appointmentId = typeof body.appointmentId === 'string' ? body.appointmentId : ''; const concerns = typeof body.patientConcerns === 'string' ? body.patientConcerns.trim().slice(0, 4000) || null : null
    if (!appointmentId) return Response.json({ error: 'An appointment is required.' }, { status: 400, headers: corsHeaders })
    const { data: appointment, error: appointmentError } = await db.from('appointments').select('id, patient_id, appointment_at, appointment_type, care_need, notes, updated_at').eq('id', appointmentId).maybeSingle()
    if (appointmentError) { console.error('Pre-consultation appointment lookup failed', appointmentError); return Response.json({ error: 'Unable to load this appointment.' }, { status: 500, headers: corsHeaders }) }
    if (!appointment || appointment.patient_id !== user.id) return Response.json({ error: 'Appointment not found.' }, { status: 404, headers: corsHeaders })
    const [{ data: records, error: recordsError }, { data: treatments, error: treatmentsError }, { data: medications, error: medicationsError }] = await Promise.all([db.from('health_records').select('record_type, title, event_date, description, provider_name, facility_name, updated_at').eq('patient_id', user.id).order('event_date', { ascending: false }).limit(25), db.from('treatments').select('title, description, status, start_date, provider_name, updated_at').eq('patient_id', user.id).in('status', ['active', 'paused']).order('updated_at', { ascending: false }), db.from('medications').select('name, dosage, frequency, status, start_date, updated_at').eq('patient_id', user.id).in('status', ['active', 'paused']).order('updated_at', { ascending: false })])
    if (recordsError || treatmentsError || medicationsError) { console.error('Pre-consultation source data error', { recordsError, treatmentsError, medicationsError }); return Response.json({ error: 'Unable to load health information for this summary.' }, { status: 500, headers: corsHeaders }) }
    const updates = [appointment.updated_at, ...(records ?? []).map((item) => item.updated_at), ...(treatments ?? []).map((item) => item.updated_at), ...(medications ?? []).map((item) => item.updated_at)].filter(isString).sort(); const sourceDataUpdatedAt = updates.at(-1) ?? appointment.updated_at
    if (body.action === 'freshness') return Response.json({ sourceDataUpdatedAt }, { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    const apiKey = Deno.env.get('GEMINI_API_KEY'); if (!apiKey) return Response.json({ error: 'PreScribe AI is not configured.' }, { status: 503, headers: corsHeaders })
    const model = (Deno.env.get('GEMINI_MODEL')?.trim() || 'gemini-3.6-flash').replace(/^models\//, ''); const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`
    const prompt = { appointment, patientProvidedConcerns: concerns, healthRecords: records ?? [], activeTreatments: treatments ?? [], activeMedications: medications ?? [] }
    const response = await fetch(endpoint, { method: 'POST', headers: { 'x-goog-api-key': apiKey, 'Content-Type': 'application/json' }, body: JSON.stringify({ systemInstruction: { parts: [{ text: instructions }] }, contents: [{ role: 'user', parts: [{ text: `Create a pre-consultation summary from only this data: ${JSON.stringify(prompt)}` }] }], generationConfig: { responseFormat: { text: { mimeType: 'APPLICATION_JSON', schema } } } }) })
    if (!response.ok) { const providerBody = await response.text(); console.error('Gemini pre-consultation provider error', { status: response.status, statusText: response.statusText, body: providerBody }); return Response.json({ error: 'The AI provider could not complete this summary.' }, { status: 502, headers: corsHeaders }) }
    const result = await response.json(); const text = result?.candidates?.[0]?.content?.parts?.find((part: { text?: unknown }) => isString(part.text))?.text; let parsed: unknown; try { parsed = isString(text) ? JSON.parse(text) : null } catch { parsed = null }
    if (!isSummary(parsed)) { console.error('Gemini pre-consultation response failed validation'); return Response.json({ error: 'The AI provider returned an invalid summary.' }, { status: 502, headers: corsHeaders }) }
    const summary = { ...parsed, generatedAt: new Date().toISOString() }
    const { error: saveError } = await db.from('pre_consultation_summaries').upsert({ patient_id: user.id, appointment_id: appointment.id, patient_concerns: concerns, summary, source_data_updated_at: sourceDataUpdatedAt }, { onConflict: 'patient_id,appointment_id' })
    if (saveError) { console.error('Unable to save pre-consultation summary', saveError); return Response.json({ error: 'The summary was created but could not be saved.' }, { status: 500, headers: corsHeaders }) }
    return Response.json({ summary, sourceDataUpdatedAt }, { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
  } catch (error) { console.error('Unable to process pre-consultation summary', error); return Response.json({ error: 'Unable to process pre-consultation summary.' }, { status: 500, headers: corsHeaders }) }
})
