-- Patient-owned treatments and medications. Safe to run more than once.
create extension if not exists pgcrypto;
create table if not exists public.treatments (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, health_record_id uuid references public.health_records(id) on delete set null, title text not null check (char_length(trim(title)) > 0), description text, treatment_type text not null check (treatment_type in ('medication','therapy','procedure','lifestyle','rehabilitation','other')), status text not null default 'active' check (status in ('active','completed','paused','discontinued')), start_date date, end_date date, provider_name text, facility_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (end_date is null or start_date is null or end_date >= start_date));
create table if not exists public.medications (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, treatment_id uuid references public.treatments(id) on delete cascade, name text not null check (char_length(trim(name)) > 0), dosage text, frequency text, route text check (route is null or route in ('oral','topical','inhalation','injection','other')), start_date date, end_date date, status text not null default 'active' check (status in ('active','completed','paused','discontinued')), instructions text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (end_date is null or start_date is null or end_date >= start_date));
create index if not exists treatments_patient_start_date_idx on public.treatments (patient_id, start_date desc); create index if not exists medications_patient_start_date_idx on public.medications (patient_id, start_date desc);
create or replace function public.set_treatment_data_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists treatments_set_updated_at on public.treatments; create trigger treatments_set_updated_at before update on public.treatments for each row execute function public.set_treatment_data_updated_at(); drop trigger if exists medications_set_updated_at on public.medications; create trigger medications_set_updated_at before update on public.medications for each row execute function public.set_treatment_data_updated_at();
alter table public.treatments enable row level security; alter table public.medications enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='treatments' and policyname='Patients manage own treatments') then create policy "Patients manage own treatments" on public.treatments for all to authenticated using (patient_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role='patient')) with check (patient_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role='patient')); end if;
  if not exists (select 1 from pg_policies where tablename='medications' and policyname='Patients manage own medications') then create policy "Patients manage own medications" on public.medications for all to authenticated using (patient_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role='patient')) with check (patient_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role='patient')); end if;
end $$;
