-- Approval-only doctor/patient relationship foundation. It grants no medical-data access.
create extension if not exists pgcrypto;
create table if not exists public.doctor_patient_connections (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, doctor_id uuid not null references public.profiles(id) on delete cascade, status text not null default 'pending' check (status in ('pending','approved','rejected','revoked')), requested_by uuid not null references public.profiles(id), request_message text, requested_at timestamptz not null default now(), responded_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (patient_id <> doctor_id));
create unique index if not exists active_doctor_patient_connection_idx on public.doctor_patient_connections(patient_id, doctor_id) where status in ('pending','approved'); create index if not exists doctor_patient_connections_doctor_idx on public.doctor_patient_connections(doctor_id, status);
create or replace function public.find_doctor_by_prescribe_id(doctor_prescribe_id text) returns table(id uuid, full_name text, prescribe_id text) language sql security definer set search_path = public as $$ select p.id, p.full_name, p.prescribe_id from public.profiles p where p.role = 'doctor' and p.prescribe_id = upper(trim(doctor_prescribe_id)) limit 1; $$; grant execute on function public.find_doctor_by_prescribe_id(text) to authenticated;
create or replace function public.get_my_patient_connections() returns table(id uuid, patient_id uuid, doctor_id uuid, status text, requested_by uuid, request_message text, requested_at timestamptz, responded_at timestamptz, created_at timestamptz, updated_at timestamptz, doctor jsonb) language sql security definer set search_path = public as $$ select c.id,c.patient_id,c.doctor_id,c.status,c.requested_by,c.request_message,c.requested_at,c.responded_at,c.created_at,c.updated_at,jsonb_build_object('id',p.id,'full_name',p.full_name,'prescribe_id',p.prescribe_id) from public.doctor_patient_connections c join public.profiles p on p.id=c.doctor_id where c.patient_id=auth.uid(); $$; grant execute on function public.get_my_patient_connections() to authenticated;
create or replace function public.enforce_doctor_patient_connection() returns trigger language plpgsql security definer set search_path = public as $$ begin if tg_op='INSERT' then if new.requested_by<>new.patient_id or new.patient_id<>auth.uid() or not exists(select 1 from profiles where id=new.patient_id and role='patient') or not exists(select 1 from profiles where id=new.doctor_id and role='doctor') then raise exception 'Invalid connection request'; end if; elsif tg_op='UPDATE' then if new.patient_id<>old.patient_id or new.doctor_id<>old.doctor_id or new.requested_by<>old.requested_by then raise exception 'Connection parties cannot be changed'; end if; if auth.uid()=old.doctor_id and old.status='pending' and new.status in ('approved','rejected') then new.responded_at=now(); elsif auth.uid()=old.patient_id and old.status='approved' and new.status='revoked' then new.responded_at=now(); else raise exception 'Invalid connection status transition'; end if; end if; new.updated_at=now(); return new; end; $$;
drop trigger if exists doctor_patient_connections_guard on public.doctor_patient_connections; create trigger doctor_patient_connections_guard before insert or update on public.doctor_patient_connections for each row execute function public.enforce_doctor_patient_connection();
alter table public.doctor_patient_connections enable row level security;
do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='doctor_patient_connections' and policyname='Participants view their connections') then create policy "Participants view their connections" on public.doctor_patient_connections for select to authenticated using (patient_id=auth.uid() or doctor_id=auth.uid()); end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='doctor_patient_connections' and policyname='Patients create own connection requests') then create policy "Patients create own connection requests" on public.doctor_patient_connections for insert to authenticated with check (patient_id=auth.uid() and requested_by=auth.uid()); end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='doctor_patient_connections' and policyname='Participants update permitted connections') then create policy "Participants update permitted connections" on public.doctor_patient_connections for update to authenticated using (patient_id=auth.uid() or doctor_id=auth.uid()) with check (patient_id=auth.uid() or doctor_id=auth.uid()); end if;
end $$;
