import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' }
const emptyCaseData = { chiefComplaint: null, symptoms: [], duration: null, onset: null, severity: null, location: null, associatedSymptoms: [], relevantMedicalHistory: null, currentMedications: null, allergies: null, additionalNotes: null }
const schema = { type: 'object', additionalProperties: false, required: ['assistantMessage', 'assistantReply', 'extractedData', 'conversationStatus', 'emergencyWarning', 'caseSummary'], properties: { assistantMessage: { type: 'string' }, assistantReply: { type: 'string' }, extractedData: { type: 'object', additionalProperties: false, required: ['chiefComplaint', 'symptoms', 'duration', 'onset', 'severity', 'location', 'associatedSymptoms', 'relevantMedicalHistory', 'currentMedications', 'allergies', 'additionalNotes'], properties: { chiefComplaint: { type: ['string', 'null'] }, symptoms: { type: 'array', items: { type: 'string' } }, duration: { type: ['string', 'null'] }, onset: { type: ['string', 'null'] }, severity: { type: ['string', 'null'] }, location: { type: ['string', 'null'] }, associatedSymptoms: { type: 'array', items: { type: 'string' } }, relevantMedicalHistory: { type: ['string', 'null'] }, currentMedications: { type: ['string', 'null'] }, allergies: { type: ['string', 'null'] }, additionalNotes: { type: ['string', 'null'] } } }, conversationStatus: { type: 'string', enum: ['collecting', 'ready_for_summary', 'emergency_warning'] }, emergencyWarning: { type: ['string', 'null'] }, caseSummary: { type: ['string', 'null'] } } }
const instructions = `You are PreScribe AI, a health-information and structured case-taking assistant. You collect and organize patient-provided information for later clinical review. You are not a doctor: never diagnose with certainty, prescribe medication, or replace professional or emergency care. Ask one concise, adaptive follow-up question at a time, using previously collected information. Only record facts the patient explicitly states; use null or [] where unknown. If the conversation suggests possible severe difficulty breathing, severe chest pressure or pain, stroke signs, loss of consciousness, severe uncontrolled bleeding, or another obvious emergency, set conversationStatus to emergency_warning, provide direct urgent-care/emergency-services guidance, and do not continue routine case-taking. Set ready_for_summary when enough practical information has been gathered, but do not invent facts. For a summary request, produce a careful organizational summary for clinical review only, based only on provided information. assistantMessage and assistantReply must contain the same patient-facing message.`

function validStringOrNull(value: unknown) { return value === null || typeof value === 'string' }
function isCaseResponse(value: unknown): value is Record<string, unknown> { if (!value || typeof value !== 'object') return false; const response = value as Record<string, unknown>; const data = response.extractedData as Record<string, unknown> | undefined; return typeof response.assistantMessage === 'string' && typeof response.assistantReply === 'string' && (response.conversationStatus === 'collecting' || response.conversationStatus === 'ready_for_summary' || response.conversationStatus === 'emergency_warning') && validStringOrNull(response.emergencyWarning) && validStringOrNull(response.caseSummary) && !!data && validStringOrNull(data.chiefComplaint) && Array.isArray(data.symptoms) && validStringOrNull(data.duration) && validStringOrNull(data.onset) && validStringOrNull(data.severity) && validStringOrNull(data.location) && Array.isArray(data.associatedSymptoms) && validStringOrNull(data.relevantMedicalHistory) && validStringOrNull(data.currentMedications) && validStringOrNull(data.allergies) && validStringOrNull(data.additionalNotes) }

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  try {
    const authorization = request.headers.get('Authorization')
    if (!authorization) return Response.json({ error: 'Authentication is required.' }, { status: 401, headers: corsHeaders })
    const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!, { global: { headers: { Authorization: authorization } } })
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) return Response.json({ error: 'Authentication is required.' }, { status: 401, headers: corsHeaders })
    const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).maybeSingle()
    if (profile?.role !== 'patient') return Response.json({ error: 'Only patient accounts can use AI Assessment.' }, { status: 403, headers: corsHeaders })
    const body = await request.json(); const messages = Array.isArray(body.messages) ? body.messages.slice(-24).filter((item) => item && (item.role === 'user' || item.role === 'assistant') && typeof item.content === 'string').map((item) => ({ role: item.role, content: item.content.slice(0, 4000) })) : []; const caseData = body.caseData && typeof body.caseData === 'object' ? body.caseData : emptyCaseData; const action = body.action === 'summary' ? 'summary' : 'message'
    if (!messages.length) return Response.json({ error: 'A conversation message is required.' }, { status: 400, headers: corsHeaders })
    const apiKey = Deno.env.get('GEMINI_API_KEY'); if (!apiKey) return Response.json({ error: 'PreScribe AI is not configured. Add GEMINI_API_KEY to the Edge Function secrets.' }, { status: 503, headers: corsHeaders })
    const configuredModel = Deno.env.get('GEMINI_MODEL')?.trim() || 'gemini-3.6-flash'
    const model = configuredModel.replace(/^models\//, '')
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`
    const geminiRequest = { systemInstruction: { parts: [{ text: instructions }] }, contents: [{ role: 'user', parts: [{ text: `Action: ${action}\nExisting case data: ${JSON.stringify(caseData)}\nConversation: ${JSON.stringify(messages)}` }] }], generationConfig: { responseFormat: { text: { mimeType: 'APPLICATION_JSON', schema } } } }
    console.info('Gemini request configuration', { model, endpoint, responseMimeType: 'APPLICATION_JSON' })
    const geminiResponse = await fetch(endpoint, { method: 'POST', headers: { 'x-goog-api-key': apiKey, 'Content-Type': 'application/json' }, body: JSON.stringify(geminiRequest) })
    if (!geminiResponse.ok) { const providerBody = await geminiResponse.text(); console.error('Gemini provider error', { status: geminiResponse.status, statusText: geminiResponse.statusText, body: providerBody }); return Response.json({ error: 'The AI provider could not complete this request.' }, { status: 502, headers: corsHeaders }) }
    const result = await geminiResponse.json(); const text = result?.candidates?.[0]?.content?.parts?.find((part: { text?: unknown }) => typeof part.text === 'string')?.text
    if (typeof text !== 'string') { console.error('Gemini response missing structured text', result); return Response.json({ error: 'The AI provider returned an invalid response.' }, { status: 502, headers: corsHeaders }) }
    let parsed: unknown; try { parsed = JSON.parse(text) } catch { console.error('Gemini returned invalid JSON', text); return Response.json({ error: 'The AI provider returned an invalid response.' }, { status: 502, headers: corsHeaders }) }
    if (!isCaseResponse(parsed)) { console.error('Gemini response failed case-taking validation', parsed); return Response.json({ error: 'The AI provider returned an invalid response.' }, { status: 502, headers: corsHeaders }) }
    return Response.json(parsed, { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
  } catch (error) { console.error(error); return Response.json({ error: 'Unable to process AI Assessment.' }, { status: 500, headers: corsHeaders }) }
})
